name: .NET Build

env:
  Solution_Name: Hemligheter.sln
  Configuration: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Nuget.exe for use with actions
        uses: Nuget/Setup-nuget@v1

      - name: Restore Nuget Packages
        run: nuget restore $env:Solution_Name
        
      - name: Create Build Directory
        run: mkdir _build

      - name: Build Solution
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform="Any CPU" /p:OutDir="./_build"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Output
          path: "./_build"
